name: Deploy

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: prod
        type: choice
        options:
          - dev
          - stg
          - prod

run-name: Deploy to AWS ${{ inputs.environment }} environment

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ENV: ${{ inputs.environment }}
  COMMIT_HASH: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # 3️⃣ Install root dependencies
      - name: Install root dependencies
        run: npm install

      - name: Display environment information
        run: |
          echo "AWS_ACCOUNT_ENV_CAPITALIZED=${AWS_ACCOUNT_ENV^}" >>${GITHUB_ENV}
          export COMMIT_HASH_SHORT=${COMMIT_HASH::7}
          echo "COMMIT_HASH_SHORT=$COMMIT_HASH_SHORT" >>${GITHUB_ENV}
          export COMMIT_DESCRIPTION_EVT_HC=$(git show -s --format=%s)
          export COMMIT_DESCRIPTION_LAST=$(git log -1 --no-merges --pretty=%B)
          export COMMIT_DESCRIPTION="${COMMIT_DESCRIPTION_EVT_HC:-$COMMIT_DESCRIPTION_LAST}"
          echo "COMMIT_DESCRIPTION=$COMMIT_DESCRIPTION" >>${GITHUB_ENV}
          env -0 | sort -z | tr '\0' '\n'

      # 4️⃣ Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # 5️⃣ Configure AWS credentials using IAM role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::221082185791:role/GitHub-Actions-Role
          aws-region: us-east-1
          role-session-name: GitHubActionsDeploy

      # 6️⃣ Deploy CDK stack
      - name: Deploy CDK
        run: |
          cd infra
          npm install
          npx cdk deploy --require-approval never